### PR TITLE
Added Discription.

### PR DESCRIPTION
**Pull request by Prashanthsai525**
Contribution to issue https://github.com/weaviate-tutorials/DEMO-multimodal-text-to-image-search/issues/1

What's being changed:
1) Wrote a short description of this project

### CODE REVIEW

**Comment by iamleonie** [comment]
Thank you for your contribution @Prashanthsai525 . Could you please add a short description of your change, including a reference/mention of the issue and I will approve and merge your PR.

**Comment by Prashanthsai525** [comment]
> Thank you for your contribution @Prashanthsai525 . Could you please add a short description of your change, including a reference/mention of the issue and I will approve and merge your PR.

**Comment by Prashanthsai525** [comment]
> > Thank you for your contribution @Prashanthsai525 . Could you please add a short description of your change, including a reference/mention of the issue and I will approve and merge your PR.

done

**Review by iamleonie — APPROVED** [review]

**Comment by iamleonie** [comment]
Thank you for your contribution!

**Pull request merged**
