### PR TITLE
added  text_to_img_clip_demo.gif to root dir, updated README 

### PR DESCRIPTION
**Pull request by CS-Edwards**
Completed @TODO in README. Added demo video/gif.

### CODE REVIEW

**Comment by CS-Edwards** [comment]
Two PRs merged:
PR1: updated readme by adding demo video
PR2: implemented and integrated python demo

Current Issues/TODO:
- [ ] Fix: ShowMore button functionality
- [ ] Updated README.md with instructions on running python demo using (start_py.sh and stop_py.sh)

**Comment by iamleonie** [comment]
Hey @CS-Edwards, 
thank you for your contribution! 
For the Python version of this demo I would like to have it in a separate repository to avoid having an extra folder called ´python` and the files ending with `-py`.

For this, I have just created a new repo as a copy from the original one here: https://github.com/weaviate-tutorials/DEMO-multimodal-text-to-image-search-py

Could you please remove the distinction between Javascript and Python and create a PR in that repo?

**Comment by CS-Edwards** [comment]
Sure, I'm going to close this PR. And open a new PR just for the readme update.

**Comment by iamleonie** [comment]
Related to https://github.com/weaviate-tutorials/DEMO-multimodal-text-to-image-search/issues/1

**Pull request closed without merging**
